//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Radsurge.MVC.EntityModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RadsurgeSQL : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RadsurgeSQL object using the connection string found in the 'RadsurgeSQL' section of the application configuration file.
        /// </summary>
        public RadsurgeSQL() : base("name=RadsurgeSQL", "RadsurgeSQL")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RadsurgeSQL object.
        /// </summary>
        public RadsurgeSQL(string connectionString) : base(connectionString, "RadsurgeSQL")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RadsurgeSQL object.
        /// </summary>
        public RadsurgeSQL(EntityConnection connection) : base(connection, "RadsurgeSQL")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DeveloperProduct> DeveloperProducts
        {
            get
            {
                if ((_DeveloperProducts == null))
                {
                    _DeveloperProducts = base.CreateObjectSet<DeveloperProduct>("DeveloperProducts");
                }
                return _DeveloperProducts;
            }
        }
        private ObjectSet<DeveloperProduct> _DeveloperProducts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Developer> Developers
        {
            get
            {
                if ((_Developers == null))
                {
                    _Developers = base.CreateObjectSet<Developer>("Developers");
                }
                return _Developers;
            }
        }
        private ObjectSet<Developer> _Developers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Listing> Listings
        {
            get
            {
                if ((_Listings == null))
                {
                    _Listings = base.CreateObjectSet<Listing>("Listings");
                }
                return _Listings;
            }
        }
        private ObjectSet<Listing> _Listings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MerchantProduct> MerchantProducts
        {
            get
            {
                if ((_MerchantProducts == null))
                {
                    _MerchantProducts = base.CreateObjectSet<MerchantProduct>("MerchantProducts");
                }
                return _MerchantProducts;
            }
        }
        private ObjectSet<MerchantProduct> _MerchantProducts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Merchant> Merchants
        {
            get
            {
                if ((_Merchants == null))
                {
                    _Merchants = base.CreateObjectSet<Merchant>("Merchants");
                }
                return _Merchants;
            }
        }
        private ObjectSet<Merchant> _Merchants;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DeveloperProducts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDeveloperProducts(DeveloperProduct developerProduct)
        {
            base.AddObject("DeveloperProducts", developerProduct);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Developers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDevelopers(Developer developer)
        {
            base.AddObject("Developers", developer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Listings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToListings(Listing listing)
        {
            base.AddObject("Listings", listing);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MerchantProducts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMerchantProducts(MerchantProduct merchantProduct)
        {
            base.AddObject("MerchantProducts", merchantProduct);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Merchants EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMerchants(Merchant merchant)
        {
            base.AddObject("Merchants", merchant);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<Results> GetSearchResults()
        {
            return base.ExecuteFunction<Results>("GetSearchResults");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="username">No Metadata Documentation available.</param>
        /// <param name="company">No Metadata Documentation available.</param>
        /// <param name="email">No Metadata Documentation available.</param>
        /// <param name="password">No Metadata Documentation available.</param>
        public ObjectResult<Nullable<global::System.Int32>> InsertDeveloper(global::System.String username, global::System.String company, global::System.String email, global::System.String password)
        {
            ObjectParameter usernameParameter;
            if (username != null)
            {
                usernameParameter = new ObjectParameter("Username", username);
            }
            else
            {
                usernameParameter = new ObjectParameter("Username", typeof(global::System.String));
            }
    
            ObjectParameter companyParameter;
            if (company != null)
            {
                companyParameter = new ObjectParameter("Company", company);
            }
            else
            {
                companyParameter = new ObjectParameter("Company", typeof(global::System.String));
            }
    
            ObjectParameter emailParameter;
            if (email != null)
            {
                emailParameter = new ObjectParameter("Email", email);
            }
            else
            {
                emailParameter = new ObjectParameter("Email", typeof(global::System.String));
            }
    
            ObjectParameter passwordParameter;
            if (password != null)
            {
                passwordParameter = new ObjectParameter("Password", password);
            }
            else
            {
                passwordParameter = new ObjectParameter("Password", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<Nullable<global::System.Int32>>("InsertDeveloper", usernameParameter, companyParameter, emailParameter, passwordParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="username">No Metadata Documentation available.</param>
        /// <param name="company">No Metadata Documentation available.</param>
        /// <param name="email">No Metadata Documentation available.</param>
        /// <param name="password">No Metadata Documentation available.</param>
        public ObjectResult<Nullable<global::System.Int32>> InsertMerchant(global::System.String username, global::System.String company, global::System.String email, global::System.String password)
        {
            ObjectParameter usernameParameter;
            if (username != null)
            {
                usernameParameter = new ObjectParameter("Username", username);
            }
            else
            {
                usernameParameter = new ObjectParameter("Username", typeof(global::System.String));
            }
    
            ObjectParameter companyParameter;
            if (company != null)
            {
                companyParameter = new ObjectParameter("Company", company);
            }
            else
            {
                companyParameter = new ObjectParameter("Company", typeof(global::System.String));
            }
    
            ObjectParameter emailParameter;
            if (email != null)
            {
                emailParameter = new ObjectParameter("Email", email);
            }
            else
            {
                emailParameter = new ObjectParameter("Email", typeof(global::System.String));
            }
    
            ObjectParameter passwordParameter;
            if (password != null)
            {
                passwordParameter = new ObjectParameter("Password", password);
            }
            else
            {
                passwordParameter = new ObjectParameter("Password", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<Nullable<global::System.Int32>>("InsertMerchant", usernameParameter, companyParameter, emailParameter, passwordParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RadsurgeEFModel", Name="Developer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Developer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Developer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        public static Developer CreateDeveloper(global::System.Int32 id, global::System.String firstName)
        {
            Developer developer = new Developer();
            developer.Id = id;
            developer.FirstName = firstName;
            return developer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Company
        {
            get
            {
                return _Company;
            }
            set
            {
                OnCompanyChanging(value);
                ReportPropertyChanging("Company");
                _Company = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Company");
                OnCompanyChanged();
            }
        }
        private global::System.String _Company;
        partial void OnCompanyChanging(global::System.String value);
        partial void OnCompanyChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RadsurgeEFModel", Name="DeveloperProduct")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DeveloperProduct : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DeveloperProduct object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="developerId">Initial value of the DeveloperId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static DeveloperProduct CreateDeveloperProduct(global::System.Int32 id, global::System.Int32 developerId, global::System.String name)
        {
            DeveloperProduct developerProduct = new DeveloperProduct();
            developerProduct.Id = id;
            developerProduct.DeveloperId = developerId;
            developerProduct.Name = name;
            return developerProduct;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DeveloperId
        {
            get
            {
                return _DeveloperId;
            }
            set
            {
                OnDeveloperIdChanging(value);
                ReportPropertyChanging("DeveloperId");
                _DeveloperId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeveloperId");
                OnDeveloperIdChanged();
            }
        }
        private global::System.Int32 _DeveloperId;
        partial void OnDeveloperIdChanging(global::System.Int32 value);
        partial void OnDeveloperIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _Type;
        partial void OnTypeChanging(Nullable<global::System.Int32> value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                OnImageUrlChanging(value);
                ReportPropertyChanging("ImageUrl");
                _ImageUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageUrl");
                OnImageUrlChanged();
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Keywords
        {
            get
            {
                return _Keywords;
            }
            set
            {
                OnKeywordsChanging(value);
                ReportPropertyChanging("Keywords");
                _Keywords = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Keywords");
                OnKeywordsChanged();
            }
        }
        private global::System.String _Keywords;
        partial void OnKeywordsChanging(global::System.String value);
        partial void OnKeywordsChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RadsurgeEFModel", Name="Listing")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Listing : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Listing object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="merchantProductId">Initial value of the MerchantProductId property.</param>
        /// <param name="developerProductId">Initial value of the DeveloperProductId property.</param>
        public static Listing CreateListing(global::System.Int32 id, global::System.Int32 merchantProductId, global::System.Int32 developerProductId)
        {
            Listing listing = new Listing();
            listing.Id = id;
            listing.MerchantProductId = merchantProductId;
            listing.DeveloperProductId = developerProductId;
            return listing;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MerchantProductId
        {
            get
            {
                return _MerchantProductId;
            }
            set
            {
                OnMerchantProductIdChanging(value);
                ReportPropertyChanging("MerchantProductId");
                _MerchantProductId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MerchantProductId");
                OnMerchantProductIdChanged();
            }
        }
        private global::System.Int32 _MerchantProductId;
        partial void OnMerchantProductIdChanging(global::System.Int32 value);
        partial void OnMerchantProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MerchantIncentive
        {
            get
            {
                return _MerchantIncentive;
            }
            set
            {
                OnMerchantIncentiveChanging(value);
                ReportPropertyChanging("MerchantIncentive");
                _MerchantIncentive = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MerchantIncentive");
                OnMerchantIncentiveChanged();
            }
        }
        private global::System.String _MerchantIncentive;
        partial void OnMerchantIncentiveChanging(global::System.String value);
        partial void OnMerchantIncentiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DeveloperProductId
        {
            get
            {
                return _DeveloperProductId;
            }
            set
            {
                OnDeveloperProductIdChanging(value);
                ReportPropertyChanging("DeveloperProductId");
                _DeveloperProductId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeveloperProductId");
                OnDeveloperProductIdChanged();
            }
        }
        private global::System.Int32 _DeveloperProductId;
        partial void OnDeveloperProductIdChanging(global::System.Int32 value);
        partial void OnDeveloperProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeveloperClaim
        {
            get
            {
                return _DeveloperClaim;
            }
            set
            {
                OnDeveloperClaimChanging(value);
                ReportPropertyChanging("DeveloperClaim");
                _DeveloperClaim = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DeveloperClaim");
                OnDeveloperClaimChanged();
            }
        }
        private global::System.String _DeveloperClaim;
        partial void OnDeveloperClaimChanging(global::System.String value);
        partial void OnDeveloperClaimChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RatingId
        {
            get
            {
                return _RatingId;
            }
            set
            {
                OnRatingIdChanging(value);
                ReportPropertyChanging("RatingId");
                _RatingId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RatingId");
                OnRatingIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RatingId;
        partial void OnRatingIdChanging(Nullable<global::System.Int32> value);
        partial void OnRatingIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> RatingScore
        {
            get
            {
                return _RatingScore;
            }
            set
            {
                OnRatingScoreChanging(value);
                ReportPropertyChanging("RatingScore");
                _RatingScore = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RatingScore");
                OnRatingScoreChanged();
            }
        }
        private Nullable<global::System.Double> _RatingScore;
        partial void OnRatingScoreChanging(Nullable<global::System.Double> value);
        partial void OnRatingScoreChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RadsurgeEFModel", Name="Merchant")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Merchant : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Merchant object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        public static Merchant CreateMerchant(global::System.Int32 id, global::System.String firstName)
        {
            Merchant merchant = new Merchant();
            merchant.Id = id;
            merchant.FirstName = firstName;
            return merchant;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Company
        {
            get
            {
                return _Company;
            }
            set
            {
                OnCompanyChanging(value);
                ReportPropertyChanging("Company");
                _Company = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Company");
                OnCompanyChanged();
            }
        }
        private global::System.String _Company;
        partial void OnCompanyChanging(global::System.String value);
        partial void OnCompanyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RadsurgeEFModel", Name="MerchantProduct")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MerchantProduct : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MerchantProduct object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="merchantId">Initial value of the MerchantId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static MerchantProduct CreateMerchantProduct(global::System.Int32 id, global::System.Int32 merchantId, global::System.String name)
        {
            MerchantProduct merchantProduct = new MerchantProduct();
            merchantProduct.Id = id;
            merchantProduct.MerchantId = merchantId;
            merchantProduct.Name = name;
            return merchantProduct;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MerchantId
        {
            get
            {
                return _MerchantId;
            }
            set
            {
                OnMerchantIdChanging(value);
                ReportPropertyChanging("MerchantId");
                _MerchantId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MerchantId");
                OnMerchantIdChanged();
            }
        }
        private global::System.Int32 _MerchantId;
        partial void OnMerchantIdChanging(global::System.Int32 value);
        partial void OnMerchantIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _Type;
        partial void OnTypeChanging(Nullable<global::System.Int32> value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                OnImageUrlChanging(value);
                ReportPropertyChanging("ImageUrl");
                _ImageUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageUrl");
                OnImageUrlChanged();
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Keywords
        {
            get
            {
                return _Keywords;
            }
            set
            {
                OnKeywordsChanging(value);
                ReportPropertyChanging("Keywords");
                _Keywords = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Keywords");
                OnKeywordsChanged();
            }
        }
        private global::System.String _Keywords;
        partial void OnKeywordsChanging(global::System.String value);
        partial void OnKeywordsChanged();

        #endregion
    
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="RadsurgeEFModel", Name="Results")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class Results : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Results object.
        /// </summary>
        /// <param name="listingId">Initial value of the ListingId property.</param>
        /// <param name="merchantProductName">Initial value of the MerchantProductName property.</param>
        /// <param name="developerProductName">Initial value of the DeveloperProductName property.</param>
        public static Results CreateResults(global::System.Int32 listingId, global::System.String merchantProductName, global::System.String developerProductName)
        {
            Results results = new Results();
            results.ListingId = listingId;
            results.MerchantProductName = merchantProductName;
            results.DeveloperProductName = developerProductName;
            return results;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ListingId
        {
            get
            {
                return _ListingId;
            }
            set
            {
                OnListingIdChanging(value);
                ReportPropertyChanging("ListingId");
                _ListingId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ListingId");
                OnListingIdChanged();
            }
        }
        private global::System.Int32 _ListingId;
        partial void OnListingIdChanging(global::System.Int32 value);
        partial void OnListingIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MerchantName
        {
            get
            {
                return _MerchantName;
            }
            set
            {
                OnMerchantNameChanging(value);
                ReportPropertyChanging("MerchantName");
                _MerchantName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MerchantName");
                OnMerchantNameChanged();
            }
        }
        private global::System.String _MerchantName;
        partial void OnMerchantNameChanging(global::System.String value);
        partial void OnMerchantNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MerchantUrl
        {
            get
            {
                return _MerchantUrl;
            }
            set
            {
                OnMerchantUrlChanging(value);
                ReportPropertyChanging("MerchantUrl");
                _MerchantUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MerchantUrl");
                OnMerchantUrlChanged();
            }
        }
        private global::System.String _MerchantUrl;
        partial void OnMerchantUrlChanging(global::System.String value);
        partial void OnMerchantUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MerchantProductName
        {
            get
            {
                return _MerchantProductName;
            }
            set
            {
                OnMerchantProductNameChanging(value);
                ReportPropertyChanging("MerchantProductName");
                _MerchantProductName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MerchantProductName");
                OnMerchantProductNameChanged();
            }
        }
        private global::System.String _MerchantProductName;
        partial void OnMerchantProductNameChanging(global::System.String value);
        partial void OnMerchantProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MerchantProductImage
        {
            get
            {
                return _MerchantProductImage;
            }
            set
            {
                OnMerchantProductImageChanging(value);
                ReportPropertyChanging("MerchantProductImage");
                _MerchantProductImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MerchantProductImage");
                OnMerchantProductImageChanged();
            }
        }
        private global::System.String _MerchantProductImage;
        partial void OnMerchantProductImageChanging(global::System.String value);
        partial void OnMerchantProductImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MerchantIncentive
        {
            get
            {
                return _MerchantIncentive;
            }
            set
            {
                OnMerchantIncentiveChanging(value);
                ReportPropertyChanging("MerchantIncentive");
                _MerchantIncentive = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MerchantIncentive");
                OnMerchantIncentiveChanged();
            }
        }
        private global::System.String _MerchantIncentive;
        partial void OnMerchantIncentiveChanging(global::System.String value);
        partial void OnMerchantIncentiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeveloperName
        {
            get
            {
                return _DeveloperName;
            }
            set
            {
                OnDeveloperNameChanging(value);
                ReportPropertyChanging("DeveloperName");
                _DeveloperName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DeveloperName");
                OnDeveloperNameChanged();
            }
        }
        private global::System.String _DeveloperName;
        partial void OnDeveloperNameChanging(global::System.String value);
        partial void OnDeveloperNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DeveloperProductName
        {
            get
            {
                return _DeveloperProductName;
            }
            set
            {
                OnDeveloperProductNameChanging(value);
                ReportPropertyChanging("DeveloperProductName");
                _DeveloperProductName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DeveloperProductName");
                OnDeveloperProductNameChanged();
            }
        }
        private global::System.String _DeveloperProductName;
        partial void OnDeveloperProductNameChanging(global::System.String value);
        partial void OnDeveloperProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeveloperProductImage
        {
            get
            {
                return _DeveloperProductImage;
            }
            set
            {
                OnDeveloperProductImageChanging(value);
                ReportPropertyChanging("DeveloperProductImage");
                _DeveloperProductImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DeveloperProductImage");
                OnDeveloperProductImageChanged();
            }
        }
        private global::System.String _DeveloperProductImage;
        partial void OnDeveloperProductImageChanging(global::System.String value);
        partial void OnDeveloperProductImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeveloperProductClaim
        {
            get
            {
                return _DeveloperProductClaim;
            }
            set
            {
                OnDeveloperProductClaimChanging(value);
                ReportPropertyChanging("DeveloperProductClaim");
                _DeveloperProductClaim = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DeveloperProductClaim");
                OnDeveloperProductClaimChanged();
            }
        }
        private global::System.String _DeveloperProductClaim;
        partial void OnDeveloperProductClaimChanging(global::System.String value);
        partial void OnDeveloperProductClaimChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeveloperProductUrl
        {
            get
            {
                return _DeveloperProductUrl;
            }
            set
            {
                OnDeveloperProductUrlChanging(value);
                ReportPropertyChanging("DeveloperProductUrl");
                _DeveloperProductUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DeveloperProductUrl");
                OnDeveloperProductUrlChanged();
            }
        }
        private global::System.String _DeveloperProductUrl;
        partial void OnDeveloperProductUrlChanging(global::System.String value);
        partial void OnDeveloperProductUrlChanged();

        #endregion
    }

    #endregion
    
}
